#Requires -Version 5.1
<#
.SYNOPSIS
    Collect TT-Core diagnostics into a timestamped report file.

.PARAMETER Root
    TT-Core root folder. Default: %USERPROFILE%\stacks\tt-core

.PARAMETER OutDir
    Output directory for diagnostic reports. Default: <Root>\diagnostics
#>
param(
  [string]$Root   = (Join-Path $env:USERPROFILE 'stacks\tt-core'),
  [string]$OutDir = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (!$OutDir) { $OutDir = Join-Path $Root "diagnostics" }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

$stamp   = (Get-Date).ToString("yyyyMMdd_HHmmss")
$outFile = Join-Path $OutDir "TT-Core_Diag_$stamp.txt"

$coreDir = Join-Path $Root "compose\tt-core"
. "$PSScriptRoot\lib\RuntimeEnv.ps1"
$coreEnvFile = Resolve-TTCoreEnvPath -RootPath $Root

Push-Location $coreDir
try {
  $sb = [System.Text.StringBuilder]::new()

  $sb.AppendLine("# TT-Core Diagnostics — $stamp") | Out-Null
  $sb.AppendLine("# Generated by: Diag.ps1") | Out-Null
  $sb.AppendLine("") | Out-Null

  # Docker version
  $sb.AppendLine("## docker version") | Out-Null
  $sb.AppendLine((docker version)) | Out-Null
  $sb.AppendLine("") | Out-Null

  # Compose ps
  $sb.AppendLine("## docker compose ps (all addon files included)") | Out-Null
  $addonFiles = Get-ChildItem (Join-Path $coreDir "addons") -Filter "*.yml" |
                Where-Object { $_.Name -notlike "00-template*" } | Sort-Object Name
  $composeArgs = @("-f", "docker-compose.yml")
  foreach ($f in $addonFiles) { $composeArgs += "-f", $f.FullName }
  $composeArgs += "--env-file", $coreEnvFile, "ps"
  $sb.AppendLine((docker compose @composeArgs)) | Out-Null
  $sb.AppendLine("") | Out-Null

  # docker ps filtered to tt- containers
  $sb.AppendLine("## docker ps (tt-core containers)") | Out-Null
  $sb.AppendLine((docker ps --filter "name=tt-core" --format "table {{.Names}}`t{{.Status}}`t{{.Ports}}")) | Out-Null
  $sb.AppendLine("") | Out-Null

  # Resource usage
  $sb.AppendLine("## docker stats (no-stream)") | Out-Null
  $sb.AppendLine((docker stats --no-stream --filter "name=tt-core")) | Out-Null
  $sb.AppendLine("") | Out-Null

  # Port listeners (all TT-Core ports)
  $sb.AppendLine("## port listeners (TT-Core ports)") | Out-Null
  $ttPorts = @(15432,16379,15678,15050,15540,13010,18082,18081,11434,13000,16333,16334,13001,19000,18789)
  foreach ($p in $ttPorts) {
    try {
      $conn = Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction Stop
      $sb.AppendLine("  Port $p : LISTENING on $($conn.LocalAddress -join ',')") | Out-Null
    } catch {
      $sb.AppendLine("  Port $p : not listening") | Out-Null
    }
  }
  $sb.AppendLine("") | Out-Null

  # .env contents (passwords masked)
  $envPath = $coreEnvFile
  if (Test-Path $envPath) {
    $sb.AppendLine("## runtime core env (secrets masked)") | Out-Null
    $envLines = Get-Content $envPath
    foreach ($line in $envLines) {
      if ($line -match "PASSWORD|SECRET|KEY|TOKEN" -and $line -match "=.+") {
        $masked = $line -replace "=.+$", "=***MASKED***"
        $sb.AppendLine($masked) | Out-Null
      } else {
        $sb.AppendLine($line) | Out-Null
      }
    }
    $sb.AppendLine("") | Out-Null
  }

  [IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
} finally {
  Pop-Location
}

Write-Host "OK: Diagnostics saved → $outFile" -ForegroundColor Green
